DB-5662: Add code standards check & apply fixes.
pantheon-systems/decoupled-kit-acf pull request #3
Opened 2023-03-20 12:46 UTC by abhisekmazumdar

2023-03-21 12:37 UTC, backlineint requested changes
@abhisekmazumdar could you remove the testing related content here for now? We don't have tests yet, and I don't believe this PR contains all of the files/config necessary for phpunit to run.

2023-03-23 01:53 UTC, backlineint requested changes
Added some comments inline. I'm expecting that it should be possible to run the linting commands here when checking out only this repository. That will help for CI in the future (could have been clearer about that in the ticket - sorry.)

We'll need to fix a few things to make that possible.

2023-03-23 01:53 UTC, backlineint commented on composer.json
> +      "dealerdirect/phpcodesniffer-composer-installer": true,
Indentation is off here.

2023-03-23 01:53 UTC, backlineint commented on composer.json
> +        "wpackagist-plugin/advanced-custom-fields": "^6.0",
For CI purposes, it should be possible to run composer install within this plugin. Currently that will fail due to the reference to wpackagist-plugin.

That can be solved by adding the following repositories section to composer.json:

```
    "repositories": [
      {
        "type": "composer",
        "url": "https://wpackagist.org",
        "only": [
          "wpackagist-plugin/*",
          "wpackagist-theme/*"
        ]
      }
    ],
```

2023-03-23 01:53 UTC, backlineint commented on composer.json
> +      "lint:php": "find ./wp-decoupled-preview.php ./src ./templates -name '*.php' -exec php -l {} \\;",
The lint php command will fail because it references files for decoupled preview, along with paths that this plugin doesn't currently use.

2023-03-23 14:32 UTC, backlineint requested changes
In a clone of this repo I can `composer install`, but `composer lint` is failing. Here's the output: https://app.warp.dev/block/l1erxrAsUnmD6lXmTlvRQc

It looks like `composer lint:php` passes, but `composer lint:phpcs` is failing.

2023-03-24 09:12 UTC, abhisekmazumdar commented
Also what are our call in composer.lock. [wp-decoupled-preview](https://github.com/pantheon-systems/wp-decoupled-preview/blob/main/composer.lock) dose have composer.lock file committed.

2023-03-27 22:17 UTC, backlineint commented
> Also what are our call in `composer.lock`. [wp-decoupled-preview](https://github.com/pantheon-systems/wp-decoupled-preview/blob/main/composer.lock) dose have `composer.lock` file committed.

I had it on my list to ask about that for the preview plugin. For now, let's not commit the lock file here.

2023-03-27 22:19 UTC, backlineint commented
> Looks like there is some issue with `php8.1^`.
> 
> [squizlabs/PHP_CodeSniffer#3677 (comment)](https://github.com/squizlabs/PHP_CodeSniffer/issues/3677#issuecomment-1290772013)
> 
> I found that (from the above issue link) we can use: `-d error_reporting="E_ALL&~E_DEPRECATED"`
> 
> Some like this:
> 
> ```shell
> vendor/bin/phpcs -d error_reporting="E_ALL&~E_DEPRECATED" -s --standard=Pantheon-WP decoupled-kit-acf.php
> ```
> 
> Looks like it will ignore all the deprecated error messages.
> 
> I can confirm that this only happen with php8.1. If I run the same commands inside lando/ddev without the changes it works. As they have `php7.4.33`.
> 
> So we will need to replace the script part to something like this:
> 
> ```shell
> "scripts": {
>     "lint:php": "find ./decoupled-kit-acf.php -name '*.php' -exec php -l {} \\;",
>     "lint:phpcs": "vendor/bin/phpcs -d error_reporting=\"E_ALL&~E_DEPRECATED\" --ignore=\"wp-content/*, tests/*\" -s --standard=Pantheon-WP .",
>     "lint:phpcbf": "vendor/bin/phpcbf -d error_reporting=\"E_ALL&~E_DEPRECATED\" --ignore=\"wp-content/*, tests/*\" -s --ignore=tests/* --standard=Pantheon-WP .",
>     "lint": "composer lint:php && composer lint:phpcs"
>   }
> ```

Thanks - this allowed me to work around this. Pushed an commit up that includes this update.

2023-03-27 22:24 UTC, backlineint approved these changes

2023-03-27 22:24 UTC, merged